apiVersion: v1
kind: Service
metadata:
  name: news-application-service
  namespace: default
  labels:
    name: news-application-service
spec:
  type: NodePort
  ports:
  - port: 9201
    nodePort: 30005
    targetPort: 9201
    protocol: TCP

  selector:
    name: news-application
    deploymentType: GREEN
