apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: news-application-green
  namespace: devopspoc
  labels:
    name: news-application
    service: news-application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: news-application
      type: frontend
  template:
    metadata:
      labels:
        name: news-application
        type: frontend
        version: "1"
        deploymentType: GREEN
    spec:
      containers:
      - name: news-application
        image: nisumpk/news_application
        ports:
        - containerPort: 9201
        env:
        - name: SERVER_PORT
          value: -Dserver.port=9201
        - name: DISCOVERY_SERVER_URL
          value: "-Deureka.client.serviceUrl.defaultZone=http://discovery-server-service:7001/eureka/"
        - name: BIZ_APPLICATION_URL
          value: "-Dbiz.application.url=http://biz-application-service:9601"
        command: ["java"]
        args: ["$(SERVER_PORT)", "$(BIZ_APPLICATION_URL)", "$(DISCOVERY_SERVER_URL)",  "-Deureka.instance.preferIpAddress=true", "-Deureka.instance.ipAddress=news-application-service", "-jar", "/usr/src/news-application-SNAPSHOT.jar"]
