apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: news-application-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8060
      name: http8060
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: news-application-virtualservice
  namespace: canary
spec:
  gateways:
  - news-application-gateway
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: news-application
        subset: news-application-production
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: news-application-dr
  namespace: canary
spec:
  host: news-application
  subsets:
  - name: news-application-production
    labels:
      version: news-application-production
  - name: news-application-uat
    labels:
      version: news-application-uat